/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_proof_recorder_service_jni_MP3Decoder_Feature */

#ifndef _Included_org_proof_recorder_service_jni_MP3Decoder_Feature
#define _Included_org_proof_recorder_service_jni_MP3Decoder_Feature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_proof_recorder_service_jni_MP3Decoder_Feature
 * Method:    isFeatureSupported
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_proof_recorder_service_jni_MP3Decoder_00024Feature_isFeatureSupported
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
