/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_proof_recorder_service_jni_Encoding */

#ifndef _Included_org_proof_recorder_service_jni_Encoding
#define _Included_org_proof_recorder_service_jni_Encoding
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
