/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_proof_recorder_service_jni_Encoding_Format */

#ifndef _Included_org_proof_recorder_service_jni_Encoding_Format
#define _Included_org_proof_recorder_service_jni_Encoding_Format
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
